Repository Bluesy1/CharB0T, pull requests merged in 2022-10, with the labels that each got.

#231 Add unittests for banners
  charbot/betas/__init__.py
  charbot/betas/_types.py
  charbot/betas/banner.py
  charbot/betas/cog.py
  charbot_rust/Cargo.lock
  tests/charbot/conftest.py
  tests/charbot/media/test_avatar.png
  tests/charbot/media/test_avatar.png.license
  tests/charbot/media/test_banner_gradient_color.png
  tests/charbot/media/test_banner_gradient_color.png.license
  tests/charbot/media/test_banner_image_background.png
  tests/charbot/media/test_banner_image_background.png.license
  tests/charbot/media/test_banner_solid_color.png
  tests/charbot/media/test_banner_solid_color.png.license
  tests/charbot/media/test_image.jpeg
  tests/charbot/media/test_image.jpeg.license
  tests/charbot/test_banners.py
Labels: python

#236 Fix giveaway code so it rejects bids of size 0 and 32768
  charbot/giveaway.py
  i18n/en-US/giveaway.ftl
Labels: bug

#244 Add __slots__ to program classes
  charbot/betas/views/banner.py
  charbot/bot.py
  charbot/pools.py
  charbot/programs/minesweeper.py
  charbot/programs/shrugman/modal.py
  charbot/programs/shrugman/view.py
  charbot/programs/sudoku/block.py
  charbot/programs/sudoku/cell.py
  charbot/programs/sudoku/column.py
  charbot/programs/sudoku/puzzle.py
  charbot/programs/sudoku/row.py
  charbot/programs/sudoku/view.py
  charbot/programs/tictactoe.py
  tests/charbot/test_shrugman.py
  tests/charbot/test_sudoku.py
  tests/charbot/test_tictactoe.py
Labels: enhancement, python

#251 Refractor dependencies to pyproject.toml
  .github/workflows/ci.yml
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: enhancement, dependencies, python

#249 Bump python to 3.11
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .github/workflows/reuse.yml
  charbot/__init__.py
Labels: enhancement, github_actions, python

#256 Add tests for giveaway code
  charbot/bot.py
  charbot/giveaway.py
  pyproject.toml
  tests/charbot/test_giveaway.py
Labels: python

#248 Refractor `giveaway.py` into a package based cog
  charbot/giveaway/__init__.py
  charbot/giveaway/cog.py
  charbot/giveaway/modal.py
  charbot/giveaway/view.py
  tests/charbot/test_giveaway.py
Labels: enhancement, python
